# Generated by Django 4.0 on 2021-05-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_about', models.TextField(max_length=100)),
                ('author_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('slug', models.CharField(default='slug', max_length=255, unique=True)),
                ('post', models.TextField(default='')),
                ('post_date_created', models.DateTimeField(auto_now_add=True)),
                ('post_date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default='Autor', on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
