# Generated by Django 4.0 on 2021-05-28 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='author_date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
