# Generated by Django 4.0 on 2021-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_about',
            field=models.TextField(max_length=255),
        ),
    ]
