# Generated by Django 4.0 on 2021-05-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_author_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_about',
            field=models.TextField(),
        ),
    ]
