# Generated by Django 4.0 on 2021-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='altura',
            field=models.IntegerField(default=130),
        ),
        migrations.AddField(
            model_name='author',
            name='largura',
            field=models.IntegerField(default=131),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(height_field=models.IntegerField(default=130), upload_to='authors', width_field=models.IntegerField(default=131)),
        ),
    ]
