# Generated by Django 4.0 on 2021-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_author_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
